Updating expeditor configuration
chef/win32-ipc pull request #31
Opened 2021-07-02 08:04 UTC by jayashrig158

Signed-off-by: jayashri garud <jgarud@msystechnologies.com>

### Description

i) The merge_actions subscription shortcut has been deprecated. All subscriptions should be declared via the subscriptions block for clarity.
ii) The promote block has been deprecated. All actions should be declared via the subscriptions block for clarity.
iii)  Release branches are a first-class concept in Expeditor, and should be represented as such.

### Issues Resolved

[List any existing issues this PR resolves, or any Discourse or
StackOverflow discussions that are relevant]

### Check List

- [ ] New functionality includes tests
- [ ] All tests pass
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

2021-07-02 10:12 UTC, jayashrig158 commented
@tduffield  Looks like changes are correct , please suggest where it's breaking to validate config

2021-07-02 13:11 UTC, tduffield requested changes

2021-07-02 13:11 UTC, tduffield commented on .expeditor/config.yml
> +  - master:
If `ffi` is their default branch, we should change this from `master` to `ffi` for them.

2021-07-02 13:20 UTC, tduffield approved these changes

2021-07-02 13:22 UTC, tduffield commented
@jayashrig158 It looks like while this project has an Expeditor config file, it isn't properly wired up. I'll make a note to get that sorted out as part of your PR. Thanks!

2025-09-17 23:35 UTC, johnmccrae commented
4 years stale. Closing

2025-09-17 23:35 UTC, closed without merging